name: Bundle Check

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Dependencies
        run: corepack enable && yarn && yarn addon
      - name: Rebuild Natives
        run: yarn electron-rebuild
      - name: Build
        run: yarn bundle-release