name: Autotest

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: yarn
      - run: corepack enable
      - run: yarn
      - run: yarn bundle-autotest
      - run: yarn test
